on: pull_request

name: Review

env:
  COMPOSE_USER: runner

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  composer-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer files
        run: |
          docker compose run --rm phpfpm composer validate
      - name: Check that dependencies resolve
        run: |
          docker compose run --rm phpfpm composer update

  check-composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm composer normalize --dry-run

  coding-standards-check-phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose run --rm phpfpm composer install
          docker compose run --rm phpfpm composer coding-standards-check/phpcs

  coding-standards-check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose run --rm markdownlint markdownlint '**/*.md'

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/code-analysis

  proxy-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/generate-proxy-classes
      - name: Check nothing has changed
        run: git diff --exit-code

  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/rector
      - name: Check nothing has changed
        run: git diff --exit-code

  coding-standards-check-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose run --rm node npm install
          docker compose run --rm node npm run coding-standards-apply
          docker compose run --rm node npm run coding-standards-check

  coding-standards-check-assets-built:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose run --rm node npm install
          docker compose run --rm node npm run build
      - name: Check that nothing has changed
        run: git diff --exit-code
